[deploy]
bucket = 'cfn-artifacts-cruddur-molsen'
region = 'us-west-1'
stack_name = 'CrdSrv'

[parameters]
NetworkingStack = 'CrdNet'
SecurityStack = 'CrdSec'
DdbStack = 'CrdDdb'
ClusterStack = 'CrdCluster'