[deploy]
bucket = 'cfn-artifacts-cruddur-molsen'
region = 'us-west-1'
stack_name = 'CrdDb'

[parameters]
NetworkingStack = 'CrdNet'
SecurityStack = 'CrdSec'
ClusterStack = 'CrdCluster'
MasterUsername = 'cruddur'