[deploy]
bucket = 'cfn-artifacts-cruddur-molsen'
region = 'us-west-1'
stack_name = 'CrdCicd'

[parameters]
ClusterStack = 'CrdCluster'
ServiceStack = 'CrdSrv'
ArtifactBucketName = 'codepipeline-cruddur-artifacts-mjolsen'
BuildSpec= 'backend-flask/buildspec.yml'
GithubBranch = 'prod'
GithubRepo = 'mjolsen-sw/aws-cruddur'